language: node_js
node_js:
  - "10"
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
before_script:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
script: yarn build
after_success:
  - aws_access_key_id=${AWS_ACCESS_KEY_ID} aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} aws s3 rm s3://sh.diogocardoso.me --recursive --region eu-west-2
deploy:
  provider: s3
  access_key_id:
    secure: ScXunjYOlMwhNxRAXfuwSfal8dMnu+5vSpVGtFjHKQ72vLQKDxFjp11QvoQNRnn9OO8GP1oj9D7WzY1CwD85D2kr113T0b20fWS5Eth5oegCn5sKzyiFGtHoA0srdGaJNvy3dcNZP4n0/jsAX+haauFlkTWVtjx+AyTyQn2S862QFhke07FN4FSCYjA+n20k7ulZDSgo4DV6IZjlMX4aznm8td25gkXZBgHmrQNqR/n4igDQqi8zZyxQCo8KnfuCoa7gZNxH/1hcw/6BzsOg5b6Vym8G3GI51FD5zqweEPDs2yqazY7XuheaX99U541lLqXpb5ShxnssjNL9QR6VERJy61fY/fYw1/VvorsRP1RS6peX2pouAn1Jga9vExVNhmRPdgeipWzbUG5E8+PCsKoz5vD2UB1dMOriXIipv0CHuurVEv6guSo5bUBi+0hl21x7Ul6IcEcp+WBF3Mm2u5aeqfxaYqH6ZHUcNHF/r8MBJUHW9flr2SXk0TTFNmcoKgql2/udHv294LTtXv5LX4xssXer/ifqktnQkJV6SWuOEFlGLoSkaOGHcPQfOAhcAPjuS/6rAr9Zw32qtkIO05+z4z9XLVcd/QZ2vzZ+imeQL8h9YiVtkjyEmM9rSA+34FoQ6yyYHkGCiF5XZqrJyYM2nLTlQgVx9AZXMMtRkkM=
  secret_access_key:
    secure: Vz4MS2Bu+rEUTVB42MQd9qllU61SR0jQTOMOPgqC8wnu0cNGm0uMiCYHUFEkwsL9/Y7pdHaOdg+6dcZZV0xnqOpHpMcqshhvSk2L8XZ5MQ3XkeFOZmfn3zL/moTteI+odOO90iqRMWIm/4pCAHIqraEVXL+KhRHCPAncW5cr4wKJVyjd89SfUonQcgXWokCnIxYMUQkYZ/Tq6q1PWGrcNDDVSkc2OGZ+i8VFBjaWPboX4K2L/CZcR255zCPgFMvJIjfB7mGPqKfVNIvX21H+jnwFKWjiAsrT6aQcM3TkqDKezKVLPsfSavYJZp3uJjgSzdBMhMwHXG35Ud3QurVQBly3h22Vr3xbzOCyOH1JOAOzM4RkOqK0hDwCcHrlqH5pbEJVj1f/nq2+CovLLBEhOoYBUJ0fLn9XMiYxgp6raEhmH9LkQ0wd5HQFg+VgRwJqVzu3av/cu7IHaHWHdQl67e6sk6AUAKmNFvpItkL0Ya5j99I1Gde+n0rXaPgXPmPecnfXGitx7Pj2x3jPcb5FzxpqIpCCcQVKyISBXVKSughb/467V7/9knFq7wmQtc4DnYrl/gVCilGcx5PgPyW19ekB4sB11xgqZOQUDLpAb/ZIwVaJOlquG6LqtG16BuGvw6CRD8VUGYO/IK+TKqzuW3RSehau4Qa7GYga7ctQT4Y=
  bucket: diogocardoso.me
  # Prevent Travis from deleting the build artifacts
  skip_cleanup: true
  region: eu-west-2
  # Deploy a single folder and not the entire project
  local_dir: public
after_deploy:
  - aws_access_key_id=${AWS_ACCESS_KEY_ID} aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --paths "/*"
notifications:
  email: false
env:
  global:
    # CF_DISTRIBUTION_ID - Cloudfront Distribution ID
    - secure: "aV5zksN++DaQmz4x+Ht35Fvay0/pC1kGglT5dZWwtZFu25pAfqm8X5eSR7N1r7zWvnmhpDf/qhCvW9weJRsUOsOeuW/YWMg51qdQLY5y/+DHTQgQ/YlXhH1eQOb3cBPrKHHcwUg4ID65n5QfuCLYpd2ZKQlZv0KaASy3rUJMTC194UqjwOE3NbOy0bXlMkAo7TAM8BE4e+7szdVkVqghwT8F2AHfoKv2UxFjR3HJIzkxO9463If5kL5DT7eteYvsEjwJ/an8vIAb/M8knhQrqDDm4bWxXPVkDYK7k1e4H59z7G6yi9FdpRM7apxRwcfpxaczbtzg9vOHFlM0ABKKaFrwHAozFHwhAhqHMcaiNGzGrNnS+XNQYz7JTrLTX+9jQrUnQ4e3enEMFopjr0N/vYRqNKfa9pexUyfgpkUxsaNWJCXwdxwvQ/+BGoGM68vZuY6kB7lBcC752U6DRM1szk4N5Bv5CyX8LY4KkciHPuKh3I5Co6Gre1vMJIg2X27nC9P8pCBeucCPB3HGcBwiQO2BO8IqEVtgz0lGFUJICGMQ9B5ov12FnaQwHlFSJyV7f3H0PQAI5Xz0eWwtn8JwAKIAgbEweihHeXlcUiY7MuxywncQaLNpsszHd7tqXZ1dpsM1SBK3XVZBHNDaWXRP8sYC/tQNQ6DXByMVITV0zQU="
    # AWS_ACCESS_KEY_ID - AWS Access Key ID
    - secure: "k678CzBcfTzwUFhsFQay1548qhJMGLvb9JXOTwmzb81VlCi0n4zeqkndbK+iZTNL/C9yUwIsL9+Zvaa5jqfqEwG7ZEXvKSNixnrvA/Ps4s37K6R9bSlYkgzA9soyvpBHQAvsQer/+GfgfAD+d2Hf8IRXtg+UtYeQEyq5mrWwSnfhRNWFviBZHVZS4AuiSwfi2HXdHeqqe+4R6mKGdR9z7i10yE+mqcYlQZvpc5NwwNAnMNh8pxKZ7RyEum+08xJveTlh7pRp/Bbymla6jEB6XJrZmYznrl6Duf9coeKm6+0Fs8y1PXcm+tFWLlYXJoqOcFc0corY7N7wTqv2Hd1IikPqBtk6EgwHQMlKs2XX5ChQMw7UrkXYlpIKEgy/lg441YUhAjyQ5bf3UH/ydjj9n9yjo1wbGSDfep1CMUcosm96+sRL5f+RxSeZILVDSgwFA5brE/O6dSjy8HFsanKEGdzSlXsSe5YjwCfeYSd3+QaZi5kZEcLyBMLz/J8NuAV3D33t9RO67pEnEMTOKME4rESkzoKf63nFnBDIo+koRFi/piGkhQ2A3CyKC5UwVWoApo8gNjShZarSyKofm8HOEVVvs7m/9fjppCpAvrLLXyHzuh40+ike8cOECbJsnkwOYpVjC73OByN85s3LizcXxdTXZPr/rZkL8pXFcXZQjsY="
    # AWS_SECRET_ACCESS_KEY - AWS Secret Access Key
    - secure: "Fkd2eSPwwJjRaeyc0oD4aXyAfGL4efmYJ1HJPH4z0xx1EDqj6qSzJJbqC5E+Kl3c3IPH+Pg53Xyqpmwvbg0/gTxAvAzyb8DgT1v+30TSE9xPV8DXlK6Bb41SieaC+19uAw1Pys3sr3NNXLC8UpbCXToIxIwOZyDJJwb0l3IS2oM1aaM8hYZEP9LPO2E8R9I5QpzRYYkjx9DsiijBJSpGmSIPJnTKyiClVubZlUq3QG5Bt1brOkCPF8H/vdHQZ8P3tIvFIsXQyLUgn02JmCCvTzdOa3/5Zdvdfwe/2+IXFgQ+IoSY+rdQz9TPjzpBbPI8ciJlLW2DRczWStJ9RnG/3AQtPuxVF9rGjNrgQqVcxruPUtrH8WVS7PeG5k73HQgNbN2hCmn5G5PfiIiu2VnjX16MdoH3Yyc+NMfdGVjNgVhX/zOlplIHjUOTLEsUhc+yuYyaUgOjLJoNKr6Q8oZOXsy6KGxXVJyvFqaCyPqR0Us2V7sUjwrFURfuVn6HEbmdGLhdk+BxtWOjLfzsChxoy1PPxqj7n1LyKH5z9mYzLWctn8LAV6DKEKpz4aU7tAl2h/yq4hi+eqod4Y1DRlBkZmJPhQlo9nzz5MmCi2epC8btjuRfpRMsPngzf6ZYLlMZodb8qNwBzNkY+ralOzw5s8MWEYSOHiSu/L2GC8VY9kY="
